targets:
  $default:
    builders:
      hive_generator|hive_generator:
        enabled: true
      riverpod_generator|riverpod_generator:
        enabled: true
        options:
          # Generate providers with .g.dart extension
          generate_riverpod_annotation: true
